# Do NOT update manually; changes here will be overwritten by Copier
_commit: edb24fc
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 8.0
rebel_module_groups: []
repo_description: opnsynid-web
repo_name: opnsynid-web
repo_slug: opnsynid-web
travis_apt_packages: []
travis_apt_sources: []
